//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerTable
    {
        public int Id { get; set; }
        public string KucukBaslik { get; set; }
        public string BuyukBaslik { get; set; }
        public string OrtaBaslik { get; set; }
        public string Resim { get; set; }
    }
}
