//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int Id { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<decimal> AlisFiyati { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public Nullable<decimal> ToplamFiyat { get; set; }
        public Nullable<System.DateTime> Saat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Musteri1 Musteri1 { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
