//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SliderTable
    {
        public int id { get; set; }
        public string SmallTitle { get; set; }
        public string MediumTitle { get; set; }
        public string BigTitle { get; set; }
        public string Description { get; set; }
        public string CoverImage { get; set; }
    }
}
